GET  http://localhost:3001/api/notes/
###
POST  http://localhost:3001/api/notes
content-type: application/json

{
    "content": "lol",
    "important": true
}
### update note
PUT http://localhost:3001/api/notes/605a1ec538834210dd71299d
content-type: application/json

{
    "content": "more updated samples",
    "important": true
}

### Users
GET http://localhost:3001/api/users/

### post users
POST http://localhost:3001/api/users/
content-type: application/json

{
    "notes": [],
    "username": "root2",
    "name": "Superuser2",
    "password": "salainen2"
}

### Add note by user
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "another note by user",
    "important": false,
    "userId": "6060a15248c858ad83ae1961"
}